# Generated by Django 3.2.6 on 2022-03-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactData',
            new_name='ContactUser',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
