# Generated by Django 3.2.6 on 2022-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
